# aynce/await function always returns a `promise`
- async function returns a promise instead of a value? <br/>
https://stackoverflow.com/questions/51338277/async-function-returning-promise-instead-of-value

## async/await implicitly returns promise?
- https://stackoverflow.com/questions/35302431/async-await-implicitly-returns-promise

1. an async function always returns a promise, even if the following situations:
    - no await is used
    - use await with non-promise
    - just return a number
    - even if no return! there will be a promise{undefined}
2. async function always wraps the return with promise.resolved()
    - **async function always wrap the return with promise**

> "the value you return will automatically be wrapped in a promise" by the static method Promise.resolve, i.e, if the return statement of an async function is - return x; it implicitly becomes - return `Promise.resolve(x)`;


3. **await un-wraps the promise and give you the value.**
    - but has no effect to a non-promise value
4. async function will be desugared to generator* function

## a nice summary from w3c
- https://www.w3schools.com/js/js_async.asp
> "async and await make promises easier to write"
> async makes a function return a Promise
> await makes a function wait for a Promise (fulfill)

# always get the value from `promise` with `.then`

## `.then` is a method with 2 arguments `success handler` and `error handler`
- what does .then do with promise?        
https://stackoverflow.com/questions/3884281/what-does-the-function-then-mean-in-javascript
> The Promise API proposes the following:
> 1. Each asynchronous task will return a promise object.          <br/> 
> 2. Each promise object will have a then function that can take two arguments, a success handler and an error handler. <br/>
> 3. The success or the error handler in the then function will be called **only once**, after the asynchronous task finishes.  <br/>
> 4. The **then function will also return a promise**, to allow chaining multiple calls.  <br/>
> 5. Each handler (success or error) can return a value, which will be passed to the next function as an argument, in the chain of promises.  <br/>
> 6. If a handler returns a promise (makes another asynchronous request), then the next handler (success or error) will be called only after that request is finished.

- `.catch` can catch error that happens in one of each `.then`

## something further... wrap the async function in hook 
- if not, there will be a eslint error    
https://stackoverflow.com/questions/53332321/react-hook-warnings-for-async-function-in-useeffect-useeffect-function-must-ret

# some code

## define an async function and return the response (WRONG SYNTAX EXAMPLE)
- first console: `resultOfReturn`, is a pending promise
- second console: `response`, is a value

### REASON
- 1: `resultOfReturn` runs before `getData` function, which haven't finished yet
- 2: `response` is a value since await can wait for the async function finish
- 3: async function always returns a promise so `resultOfReturn` is a promise, not a valule

### WHY IT'S WRONG
- always get value of promise by `.then`
- `resultOfReturn` doesn't get the correct value

```js
  useEffect(() => {
    const getData = async () => {
      const response = await getRedirectResult(auth);
      console.log("run 2, a value", response);
      return response;
    };
    const resultOfReturn = getData();        // ISSUE HERE
    console.log("resultOfReturn 1, a promise", resultOfReturn);
  }, []);

// get correct value by .then

getData().then((res) => console.log(res))
```

## define an async function and EXTRACT value from promise with `.then` (correct syntax of the above example)
- the response in async function is a value, no problem. (log 2)
- use `.then` to the return of the async function, we can get the value. (log 3)
- curiously, the result of `.then` is another promise. (log 1)

**`then` will not execute until a promise return from the async function** 

```js
  useEffect(() => {
    const getData = async () => {
      const response = await getRedirectResult(auth);
      console.log("run 2, a value", response);
      return response;
    };
    const resultOfThen = getData().then((res) =>
      console.log("res from then 3, a value", res)
    );
    console.log("resultOfThen 1, a promise", resultOfThen);
  }, []);

```

# execution order, async/await scope
- in async/await block, code after await will be blocked
- outside of the block, code will be executed immediately/ SYNCHRONOUSLY.
- so the console.log after the async function always gets run first.


# some notes from tony alicea - weird part of js, promises, async/await
- then only gets run AFTER the promise is resolved.

### `thennable object`
- the syntax that follow the chain of .then, each chain can deal with a promise OR NOT, .then will return a promise eventually. this structure helps, so people follows it. 

### fetch
- another example of chainning .then
